In [2]:
"HelloWorld"

'HelloWorld'

In [3]:
1+1
#shift enter to run code (works top down)
# a for cell before , b for cell after , dd to delete
# m for latex (markdown), y for code

2

3+3

In [4]:
a = 100
a
# a is a varible, assigns values right to left

100

In [5]:
(1 + 2*(3 + 4) - 7)**2/11
#rational numbers converted into floats
#usual opperations * multiply **power % module

5.818181818181818

In [2]:
#to do math import packages
import numpy as np
import matplotlib.pyplot as plt
# thus use np.(.) or plt.(.) for functions
#Note if multiple calculations it only spits out the last one, need print 

print(np.sqrt(4))

np.sin(np.pi)

print(np.cos(np.pi))

np.exp(complex(0,np.pi))

2.0
-1.0


(-1+1.2246467991473532e-16j)

In [15]:
#functions defined with "def" name of function parenthesis with arguments
# and ":" definition of funciton should be indented. retun value with return
#keyword from definition

def f(x, y, z):
    result = x**2 + 2*x*y-z**7
    return result

f(3,2,1)

20

Using markdown M you can write using laytex eg $(x^2+y^2)^(1/2)$

In [16]:
def f(x,y):
    result = (x**2 + y**2)**(1/2)
    return result

f(3,4)

5.0

In [7]:
#arrays are useful

v = np.array([4,7])
A = np.array([[3,6],[2,7]])
T = np.array([[[1,7],[4,5]],[[3,8],[9,2]]])

print(v)


print(A)
print(T)


[4 7]
[[3 6]
 [2 7]]
[[[1 7]
  [4 5]]

 [[3 8]
  [9 2]]]


In [16]:
# arrays are indexed from 0 [1:2] is everything from the 2nd up to and not including the third entry
#if multidimentional then [1,[:2]]

print(v[1])

print(A[1,1])


7
7


In [18]:
#we cant treat arrays as vectors and apply what we know to them

G = np.array([1,2])
H = np.array([3,4])

#dot prodct defined as G@H

G@H

11

In [19]:
G*H #this is element wise multiplication

array([3, 8])

In [28]:
#use dict when labeling certain elements of array


dict = {"key1" : 2, 3:11, "keyx": 7}

print(dict)
dict["keyx"]

{'key1': 2, 3: 11, 'keyx': 7}


7

In [29]:
class IdentityMatrix(object):

    def __init__(self, n,):
        """The number ``n`` gives the size of the matrix."""
        self.mat = np.identity(n)

    def tr(self):
        return np.trace(self.mat)

In [30]:
I = IdentityMatrix(3)

In [31]:
I.mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
I.tr()

3.0